apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd-neuron
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["inf2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      expireAfter: 720h # 30 * 24h = 720h
      nodeClassRef:
        name: amd-neuron
        group: karpenter.k8s.aws  # Updated since only a single version will be served
        kind: EC2NodeClass
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: amd-neuron
spec:
  amiFamily: AL2 # Amazon Linux 2
  amiSelectorTerms: 
  - alias: al2@latest
  role: $KarpenterNodeRole
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: $KarpenterDiscoveryTag
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: $KarpenterDiscoveryTag
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true
